language: python
python:
  - "3.4"
  - "3.5"
os:
  - linux

before_install:
  - sudo apt-get update
  - sudo apt-get install libpcre3 libpcre3-dev
  - sudo apt-get install -y swig3.0
install:
- pip install git+https://github.com/automl/random_forest_run.git
